main: de.theniclas.oitct.main.Main
name: OITC-T
version: 1.0.1
author: nvclas
commands:
   team:
   ac:
   startfight:
      aliases: [sf]
   map:
   spec:
      aliases: [spectate]
   kit:
   lobby:
      aliases: [l, hub, leave]
   ping:
   teamchat:
      aliases: [tc]